name: Windows

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --bin govee
    - name: Assemble archive
      shell: bash
      run: |
        mv target/release/govee.exe govee.exe
        7z a -tzip Govee2Mqtt-windows-x64.zip govee.exe AmazonRootCA1.pem assets
    - name: "Upload artifact"
      uses: actions/upload-artifact@v4
      with:
        name: "windows-x64"
        path: Govee2Mqtt*.zip
        if-no-files-found: error

